version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: overkill
      POSTGRES_PASSWORD: Usmcmarines@07
      POSTGRES_DB: overkill_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hawx.overkill@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Usmcmarines@07
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data
