version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:1.7.5
    container_name: terraform
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - /c/Users/sriva/AppData/Roaming/gcloud:/root/.config/gcloud:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    entrypoint: ["/bin/sh"]
    tty: true

  atlantis:
      image: runatlantis/atlantis
      container_name: atlantis
      ports:
        - "4141:4141"
      environment:
        ATLANTIS_GH_USER: your-github-username
        ATLANTIS_GH_TOKEN: your-github-personal-access-token
        ATLANTIS_REPO_ALLOWLIST: github.com/your-username/your-repo
        ATLANTIS_GH_WEBHOOK_SECRET: random-secret
      volumes:
        - ./repos:/repos