version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sqlpad:
    image: sqlpad/sqlpad:latest
    ports:
      - "3000:3000"
    environment:
      - SQLPAD_ADMIN=admin
      - SQLPAD_ADMIN_PASSWORD=yourpassword
    volumes:
      - sqlpad-data:/var/lib/sqlpad
    restart: unless-stopped

volumes:
  mysql_data:
  sqlpad-data: